use std::io::Error;

pub fn solve_first_star(input: &str) -> Result<String, Error> {
    todo!()
}

pub fn solve_second_star(input: &str) -> Result<String, Error> {
    todo!()
}
